---
name: HTTP-Lint
version: 1.0
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
abstract: Check HTTP messages and transactions for protocol violations
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTTP-Lint
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lkundrak/http-lint
build_requires:
  HTTP::Message: 0
  Test::Pod: 1.0
requires:
  HTTP::Message: 0
  LWP::UserAgent: 0
configure_requires:
  Module::Build: 0.35
provides:
  HTTP::Lint:
    file: lib/HTTP/Lint.pm
  HTTP::Lint::Message:
    file: lib/HTTP/Lint.pm
  HTTP::Lint::UserAgent:
    file: lib/HTTP/Lint/UserAgent.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
